image: docker:stable

stages:
  - build
  - deploy

build:
  image: node:lts
  stage: build
  script:
    - npm install
    - npm run lint
    - npm run test:coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

deploy master:
  stage: deploy
  script:
    - docker build -t registry:5000/discordbot:latest .
    - docker push registry:5000/discordbot:latest
  only:
    - master
