image: docker:latest

services:
    - docker:dind

test:
    image: node
    stage: test
    script:
        - yarn install
        - yarn lint
        - yarn test

deploy:
    stage: deploy
    script:
        - docker build -t docker.sylvainviste.com/discordbot .
        - docker push docker.sylvainviste.com/discordbot
    only:
        - master
