image: docker:stable

stages:
  - build
  - deploy

build:
  image: node
  stage: build
  script:
    - npm install
    - npm run lint
    - npm run test:coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

deploy master:
  stage: deploy
  script:
    - docker build -t registry/discordbot:latest .
    - docker push registry/discordbot:latest
  only:
    - master

deploy dev:
  stage: deploy
  script:
    - docker build -t registry/discordbot:rc .
    - docker push registry/discordbot:rc
  only:
    - dev
