image: docker:latest

services:
    - docker:dind

deploy:
    stage: deploy
    script:
        - npm run lint
        - docker build -t docker.sylvainviste.com/discordbot .
        - docker push docker.sylvainviste.com/discordbot
    only:
        - master
