image: docker:latest

services:
  - docker:dind

test:
  image: node
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test:coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

deploy:
  stage: deploy
  script:
    - docker build -t docker.sylvainviste.com/discordbot .
    - docker push docker.sylvainviste.com/discordbot
  only:
    - master
